#!/usr/bin/env python3
import subprocess, sys, re, shutil

DWARFDUMP = shutil.which("llvm-dwarfdump") or shutil.which("dwarfdump")

DIE_RE = re.compile(r'^0x[0-9a-fA-F]+:(\s*)(DW_TAG_\w+)')
NAME_RE = re.compile(r'DW_AT_name\s*\("([^"]*)"\)')
SIZE_RE = re.compile(r'DW_AT_byte_size\s*\((0x[0-9a-fA-F]+|\d+)\)')
LOC_RE = re.compile(r'DW_AT_data_member_location\s*\([^)]*?(0x[0-9a-fA-F]+|\d+)\)')
TYPE_RE = re.compile(r'DW_AT_type\s*\([^"]*"([^"]*)"\)')

SCALAR = {
    "bool": "byte", "char": "sbyte", "signed char": "sbyte", "unsigned char": "byte",
    "s8": "sbyte", "u8": "byte", "s16": "short", "u16": "ushort", "short": "short",
    "unsigned short": "ushort", "s32": "int", "u32": "uint", "int": "int", "BOOL": "int",
    "unsigned int": "uint", "s64": "long", "u64": "ulong", "long long": "long",
    "unsigned long long": "ulong", "f32": "float", "float": "float",
    "f64": "double", "double": "double",
    "int8_t": "sbyte", "uint8_t": "byte", "int16_t": "short", "uint16_t": "ushort",
    "int32_t": "int", "uint32_t": "uint", "int64_t": "long", "uint64_t": "ulong",
}


IDENT_RE = re.compile(r"^[A-Za-z_]\w*$")
KEYWORDS = {
    "abstract", "as", "base", "bool", "break", "byte", "case", "catch", "char",
    "checked", "class", "const", "continue", "decimal", "default", "delegate",
    "do", "double", "else", "enum", "event", "explicit", "extern", "false",
    "finally", "fixed", "float", "for", "foreach", "goto", "if", "implicit",
    "in", "int", "interface", "internal", "is", "lock", "long", "namespace",
    "new", "null", "object", "operator", "out", "override", "params", "private",
    "protected", "public", "readonly", "ref", "return", "sbyte", "sealed",
    "short", "sizeof", "stackalloc", "static", "string", "struct", "switch",
    "this", "throw", "true", "try", "typeof", "uint", "ulong", "unchecked",
    "unsafe", "ushort", "using", "virtual", "void", "volatile", "while",
}


def cs_type(t):
    t = t.strip()
    if not t or "[" in t:
        return None
    if t.endswith("*"):
        return "nint"
    if "::*" in t:
        return "Pmf"
    if "(*)" in t:
        return "nint"
    return SCALAR.get(t.replace("const", "").replace("volatile", "").strip())


def field_name(n):
    if not IDENT_RE.match(n):
        return None
    return "@" + n if n in KEYWORDS else n


def parse_structs(text, wanted):
    best = {}        # name -> (size, [(member, off, cstype)])
    stack = []       # [indent, name, size, members]
    cur = None

    def finalize(c):
        if c is None:
            return
        while stack and stack[-1][0] >= c["indent"]:
            ind, name, size, members = stack.pop()
            if name and size and members and (wanted is None or name in wanted):
                if name not in best or len(members) > len(best[name][1]):
                    best[name] = (size, members)
        if c["kind"] == "type":
            stack.append([c["indent"], c["name"], c.get("size"), []])
        elif c["kind"] == "member" and stack and c["name"] and c["loc"] is not None:
            ct = cs_type(c["type"] or "")
            if ct:
                stack[-1][3].append((c["name"], c["loc"], ct))

    for line in text.splitlines():
        m = DIE_RE.match(line)
        if m:
            finalize(cur)
            indent, tag = len(m.group(1)), m.group(2)
            if tag in ("DW_TAG_structure_type", "DW_TAG_class_type", "DW_TAG_union_type"):
                cur = {"kind": "type", "indent": indent, "name": None, "size": None}
            elif tag == "DW_TAG_member":
                cur = {"kind": "member", "indent": indent, "name": None, "loc": None, "type": None}
            else:
                cur = {"kind": "other", "indent": indent}
        elif cur is not None:
            if cur["kind"] in ("type", "member") and cur["name"] is None:
                nm = NAME_RE.search(line)
                if nm:
                    cur["name"] = nm.group(1)
                    continue
            if cur["kind"] == "type" and cur["size"] is None:
                sm = SIZE_RE.search(line)
                if sm:
                    cur["size"] = int(sm.group(1), 0)
            elif cur["kind"] == "member":
                lm = LOC_RE.search(line)
                if lm:
                    cur["loc"] = int(lm.group(1), 0)
                elif cur["type"] is None:
                    tm = TYPE_RE.search(line)
                    if tm:
                        cur["type"] = tm.group(1)
    finalize(cur)
    return best


def emit(structs, ns):
    out = []
    out.append("// <auto-generated> struct_gen.py from DWARF. Do not edit.")
    out.append("#pragma warning disable CS8981")
    out.append("using System.Runtime.InteropServices;")
    out.append("using Augment;")
    out.append("")
    out.append(f"namespace {ns};")
    out.append("")
    n = 0
    for name in sorted(structs):
        if not IDENT_RE.match(name):
            continue
        size, members = structs[name]
        seen = set()
        lines = []
        for mname, off, ct in members:
            fn = field_name(mname)
            if fn is None or fn in seen:
                continue
            seen.add(fn)
            lines.append(f"    [FieldOffset(0x{off:x})] public {ct} {fn};")
        if not lines:
            continue
        out.append(f"[StructLayout(LayoutKind.Explicit, Size = {size})]")
        out.append(f"public struct {name}")
        out.append("{")
        out.extend(lines)
        out.append("}")
        out.append("")
        n += 1
    return "\n".join(out), n


def main():
    dsym, listfile, outpath = sys.argv[1], sys.argv[2], sys.argv[3]
    ns = "CR.Structs"
    if "--namespace" in sys.argv:
        ns = sys.argv[sys.argv.index("--namespace") + 1]
    with open(listfile) as f:
        wanted = {ln.strip() for ln in f if ln.strip() and not ln.startswith("#")}
    if "*" in wanted:
        wanted = None
    text = subprocess.run([DWARFDUMP, "--debug-info", dsym],
                          capture_output=True, text=True, encoding="utf-8").stdout
    structs = parse_structs(text, wanted)
    src, n = emit(structs, ns)
    with open(outpath, "w") as f:
        f.write(src + "\n")
    missing = "" if wanted is None else wanted - set(structs)
    print(f"struct_gen: {n} structs -> {outpath}" +
          (f" (missing: {', '.join(sorted(missing))})" if missing else ""))


if __name__ == "__main__":
    main()
